version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
